# Generated by Django 4.2.5 on 2023-09-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('choose', models.CharField(choices=[('instagram', 'instagram'), ('facebook', 'facebook'), ('twitter', 'twitter')], max_length=9, verbose_name='scoil')),
            ],
            options={
                'verbose_name': 'sciol name',
                'verbose_name_plural': 'sciol names',
                'db_table': 'sciol_name',
            },
        ),
    ]
