# Generated by Django 4.2.5 on 2023-09-26 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create workspace')),
                ('is_active', models.BooleanField(default=True)),
                ('workspace_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wprkspace',
                'verbose_name_plural': 'workspaces',
                'db_table': 'workspace_model',
            },
        ),
    ]
