# Generated by Django 4.2.5 on 2023-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin')], max_length=9, verbose_name='scoil')),
            ],
            options={
                'verbose_name': 'workspace_home',
                'verbose_name_plural': 'workspace_homes',
                'db_table': 'workspace_home',
            },
        ),
    ]
