# Generated by Django 4.2.5 on 2023-09-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workspacemodel',
            table='workspace_model',
        ),
    ]
