# Generated by Django 4.2.5 on 2023-09-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspce', '0002_homemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='link_downloaad',
            field=models.CharField(default=0, max_length=255, verbose_name='link'),
            preserve_default=False,
        ),
    ]
