# Generated by Django 4.2.5 on 2023-09-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspce', '0004_homemodel_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='link_downloaad',
        ),
    ]
