# Generated by Django 4.2.5 on 2023-09-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspce', '0005_remove_homemodel_link_downloaad'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homemodel',
            table='sciol_name',
        ),
    ]
