# Generated by Django 4.2.5 on 2023-09-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspce', '0006_alter_homemodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homemodel',
            options={'verbose_name': 'sciol name', 'verbose_name_plural': 'sciol names'},
        ),
    ]
