# Generated by Django 4.2.5 on 2023-09-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_delete_cardmodel'),
        ('workspce', '0007_alter_homemodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkspaceModel',
        ),
    ]
