version: '3.9'


services:
  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn Downloader.wsgi -b 0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    networks:
      - main
    restart: always


  nginix:
    container_name: nginix
    command: nginix -g "deamon off;"
    depends_on:
      - app
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - /nginix.conf:/etc/nginix/nginix.conf


networks:
  main:
