# Generated by Django 4.2.5 on 2023-09-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkSciol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_sciol', models.CharField(max_length=255, verbose_name='link')),
                ('sciol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sciol_name', to='workspce.homemodel')),
            ],
            options={
                'verbose_name': 'LinkSciol',
                'verbose_name_plural': 'LinkSciols',
                'db_table': 'LinkSciol',
            },
        ),
        migrations.CreateModel(
            name='ResolotionSciolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('format', models.CharField(choices=[('148', '148'), ('240', '240'), ('360', '360'), ('720', '720'), ('1080', '1080')], max_length=4, verbose_name='resolution')),
                ('scial_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.linksciol')),
            ],
            options={
                'verbose_name': 'ResolotionSciol',
                'verbose_name_plural': 'ResolotionSciols',
                'db_table': 'ResolotionSciol',
            },
        ),
    ]
