# Generated by Django 4.2.5 on 2023-09-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkSciol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_sciol', models.URLField(max_length=255, verbose_name='link')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create link')),
            ],
            options={
                'verbose_name': 'LinkSciol',
                'verbose_name_plural': 'LinkSciols',
                'db_table': 'LinkSciol',
            },
        ),
    ]
