# Generated by Django 4.2.5 on 2023-09-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkSciol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_sciol', models.CharField(max_length=255, verbose_name='link')),
                ('sciol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sciol_name', to='workspce.homemodel')),
            ],
            options={
                'verbose_name': 'LinkSciol',
                'verbose_name_plural': 'LinkSciols',
                'db_table': 'LinkSciol',
            },
        ),
    ]
