# Generated by Django 4.2.5 on 2023-09-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspce', '0004_homemodel_create_at'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardHomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=4, verbose_name='resolution')),
                ('scial_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspce.homemodel')),
            ],
            options={
                'verbose_name': 'card_home',
                'verbose_name_plural': 'card_homes',
                'db_table': 'card',
            },
        ),
    ]
