# Generated by Django 4.2.5 on 2023-09-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResolotionSciolModel',
        ),
    ]
