# Generated by Django 4.2.5 on 2023-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksciol',
            name='link_sciol',
            field=models.URLField(max_length=255, verbose_name='link'),
        ),
    ]
