# Generated by Django 4.2.5 on 2023-09-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_linksciol_link_sciol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linksciol',
            name='sciol_name',
        ),
    ]
