# Generated by Django 4.2.5 on 2023-09-26 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_cardhomemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardhomemodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create'),
            preserve_default=False,
        ),
    ]
