# Generated by Django 4.2.5 on 2023-09-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspce', '0005_remove_homemodel_link_downloaad'),
        ('card', '0003_cardhomemodel_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhomemodel',
            name='format',
            field=models.CharField(choices=[('148', '148'), ('240', '240'), ('360', '360'), ('720', '720'), ('1080', '1080')], max_length=4, verbose_name='resolution'),
        ),
        migrations.CreateModel(
            name='LinkSciol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_sciol', models.CharField(max_length=255, verbose_name='link')),
                ('sciol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sciol_name', to='workspce.homemodel')),
            ],
            options={
                'verbose_name': 'LinkSciol',
                'verbose_name_plural': 'LinkSciols',
                'db_table': 'LinkSciol',
            },
        ),
        migrations.AlterField(
            model_name='cardhomemodel',
            name='scial_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.linksciol'),
        ),
    ]
