# Generated by Django 4.2.5 on 2023-09-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_rename_cardhomemodel_resolotionsciolmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardModel',
        ),
    ]
