# Generated by Django 4.2.5 on 2023-09-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languges', models.CharField(choices=[('english(uk)', 'English(UK)'), ('english(us)', 'English(US)'), ('persion', 'Persion'), ('arabic', 'Arabic'), ('Hindi', 'Hindi'), ('Turkish', 'Turkish')], max_length=11, verbose_name='languge')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'Language',
            },
        ),
    ]
