# Generated by Django 4.2.5 on 2023-09-26 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 26, 14, 52, 23, 755608, tzinfo=datetime.timezone.utc), verbose_name='create'),
            preserve_default=False,
        ),
    ]
